spring:
  h2:
    console:
      enabled: true
  liquibase:
    changeLog: "classpath:db/changelog/master.xml"
    default-schema: TEST
  sql:
    init:
      platform: H2
  datasource:
    url: jdbc:h2:./test;INIT=CREATE SCHEMA IF NOT EXISTS TEST\;SET SCHEMA TEST;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
